TEAM = 'MIA'

TEAM_INFO = {
    'ATL': {'full_name': 'Atlanta Hawks', 'reddit': '/r/AtlantaHawks'},
    'BOS': {'full_name': 'Boston Celtics', 'reddit': '/r/BostonCeltics'},
    'BKN': {'full_name': 'Brooklyn Nets', 'reddit': '/r/gonets'},
    'CHA': {'full_name': 'Charlotte Bobcats', 'reddit': '/r/CharlotteHornets'},
    'CHI': {'full_name': 'Chicago Bulls', 'reddit': '/r/ChicagoBulls'},
    'CLE': {'full_name': 'Cleveland Cavaliers', 'reddit': '/r/ClevelandCavs'},
    'DAL': {'full_name': 'Dallas Mavericks', 'reddit': '/r/mavericks'},
    'DEN': {'full_name': 'Denver Nuggets', 'reddit': '/r/DenverNuggets'},
    'DET': {'full_name': 'Detroit Pistons', 'reddit': '/r/DetroitPistons'},
    'GSW': {'full_name': 'Golden State Warriors', 'reddit': '/r/warriors'},
    'HOU': {'full_name': 'Houston Rockets', 'reddit': '/r/rockets'},
    'IND': {'full_name': 'Indiana Pacers', 'reddit': '/r/Pacers'},
    'LAC': {'full_name': 'Los Angeles Clippers', 'reddit': '/r/laclippers'},
    'LAL': {'full_name': 'Los Angeles Lakers', 'reddit': '/r/lakers'},
    'MEM': {'full_name': 'Memphis Grizzlies', 'reddit': '/r/memphisgrizzlies'},
    'MIA': {'full_name': 'Miami Heat', 'reddit': '/r/heat'},
    'MIL': {'full_name': 'Milwaukee Bucks', 'reddit': '/r/MkeBucks'},
    'MIN': {'full_name': 'Minnesota Timberwolves', 'reddit': '/r/timberwolves'},
    'NOP': {'full_name': 'New Orleans Pelicans', 'reddit': '/r/nolapelicans'},
    'NYK': {'full_name': 'New York Knicks', 'reddit': '/r/nyknicks'},
    'OKC': {'full_name': 'Oklahoma City Thunder', 'reddit': '/r/thunder'},
    'ORL': {'full_name': 'Orlando Magic', 'reddit': '/r/OrlandoMagic'},
    'PHI': {'full_name': 'Philadelphia 76ers', 'reddit': '/r/sixers'},
    'PHX': {'full_name': 'Phoenix Suns', 'reddit': '/r/suns'},
    'POR': {'full_name': 'Portland Timbers', 'reddit': '/r/ripcity'},
    'SAC': {'full_name': 'Sacramento Kings', 'reddit': '/r/kings'},
    'SAS': {'full_name': 'San Antonio Spurs', 'reddit': '/r/nbaspurs'},
    'TOR': {'full_name': 'Toronto Raptors', 'reddit': '/r/TorontoRaptors'},
    'UTA': {'full_name': 'Utah Jazz', 'reddit': '/r/utahjazz'},
    'WAS': {'full_name': 'Washington Wizards', 'reddit': '/r/WashingtonWizards'}
}