TEAM_TRI_TO_INFO = {
    "ATL": {"full_name": "Atlanta Hawks", "reddit": "/r/AtlantaHawks"},
    "BOS": {"full_name": "Boston Celtics", "reddit": "/r/BostonCeltics"},
    "BKN": {"full_name": "Brooklyn Nets", "reddit": "/r/gonets"},
    "CHA": {"full_name": "Charlotte Bobcats", "reddit": "/r/CharlotteHornets"},
    "CHI": {"full_name": "Chicago Bulls", "reddit": "/r/ChicagoBulls"},
    "CLE": {"full_name": "Cleveland Cavaliers", "reddit": "/r/ClevelandCavs"},
    "DAL": {"full_name": "Dallas Mavericks", "reddit": "/r/mavericks"},
    "DEN": {"full_name": "Denver Nuggets", "reddit": "/r/DenverNuggets"},
    "DET": {"full_name": "Detroit Pistons", "reddit": "/r/DetroitPistons"},
    "GSW": {"full_name": "Golden State Warriors", "reddit": "/r/warriors"},
    "HOU": {"full_name": "Houston Rockets", "reddit": "/r/rockets"},
    "IND": {"full_name": "Indiana Pacers", "reddit": "/r/Pacers"},
    "LAC": {"full_name": "Los Angeles Clippers", "reddit": "/r/laclippers"},
    "LAL": {"full_name": "Los Angeles Lakers", "reddit": "/r/lakers"},
    "MEM": {"full_name": "Memphis Grizzlies", "reddit": "/r/memphisgrizzlies"},
    "MIA": {"full_name": "Miami Heat", "reddit": "/r/heat"},
    "MIL": {"full_name": "Milwaukee Bucks", "reddit": "/r/MkeBucks"},
    "MIN": {"full_name": "Minnesota Timberwolves", "reddit": "/r/timberwolves"},
    "NOP": {"full_name": "New Orleans Pelicans", "reddit": "/r/nolapelicans"},
    "NYK": {"full_name": "New York Knicks", "reddit": "/r/nyknicks"},
    "OKC": {"full_name": "Oklahoma City Thunder", "reddit": "/r/thunder"},
    "ORL": {"full_name": "Orlando Magic", "reddit": "/r/OrlandoMagic"},
    "PHI": {"full_name": "Philadelphia 76ers", "reddit": "/r/sixers"},
    "PHX": {"full_name": "Phoenix Suns", "reddit": "/r/suns"},
    "POR": {"full_name": "Portland Timbers", "reddit": "/r/ripcity"},
    "SAC": {"full_name": "Sacramento Kings", "reddit": "/r/kings"},
    "SAS": {"full_name": "San Antonio Spurs", "reddit": "/r/nbaspurs"},
    "TOR": {"full_name": "Toronto Raptors", "reddit": "/r/TorontoRaptors"},
    "UTA": {"full_name": "Utah Jazz", "reddit": "/r/utahjazz"},
    "WAS": {"full_name": "Washington Wizards", "reddit": "/r/WashingtonWizards"},
}


TEAM_ID_TO_INFO = {
    "1610612737": {
        "city": "Atlanta",
        "fullName": "Atlanta Hawks",
        "isNBAFranchise": True,
        "confName": "East",
        "tricode": "ATL",
        "teamShortName": "Atlanta",
        "divName": "Southeast",
        "isAllStar": False,
        "nickname": "Hawks",
        "urlName": "hawks",
        "reddit": "/r/AtlantaHawks",
        "teamId": "1610612737",
        "altCityName": "Atlanta",
    },
    "1610612738": {
        "nickname": "Celtics",
        "urlName": "celtics",
        "teamId": "1610612738",
        "altCityName": "Boston",
        "tricode": "BOS",
        "teamShortName": "Boston",
        "divName": "Atlantic",
        "isAllStar": False,
        "isNBAFranchise": True,
        "confName": "East",
        "reddit": "/r/BostonCeltics",
        "fullName": "Boston Celtics",
        "city": "Boston",
    },
    "1610612751": {
        "altCityName": "Brooklyn",
        "teamId": "1610612751",
        "urlName": "nets",
        "nickname": "Nets",
        "isAllStar": False,
        "divName": "Atlantic",
        "teamShortName": "Brooklyn",
        "tricode": "BKN",
        "confName": "East",
        "isNBAFranchise": True,
        "reddit": "/r/gonets",
        "fullName": "Brooklyn Nets",
        "city": "Brooklyn",
    },
    "1610612766": {
        "nickname": "Hornets",
        "urlName": "hornets",
        "teamId": "1610612766",
        "altCityName": "Charlotte",
        "tricode": "CHA",
        "teamShortName": "Charlotte",
        "divName": "Southeast",
        "isAllStar": False,
        "isNBAFranchise": True,
        "reddit": "/r/CharlotteHornets",
        "confName": "East",
        "fullName": "Charlotte Hornets",
        "city": "Charlotte",
    },
    "1610612741": {
        "altCityName": "Chicago",
        "teamId": "1610612741",
        "urlName": "bulls",
        "nickname": "Bulls",
        "isAllStar": False,
        "divName": "Central",
        "teamShortName": "Chicago",
        "tricode": "CHI",
        "confName": "East",
        "reddit": "/r/ChicagoBulls",
        "isNBAFranchise": True,
        "fullName": "Chicago Bulls",
        "city": "Chicago",
    },
    "1610612739": {
        "urlName": "cavaliers",
        "nickname": "Cavaliers",
        "altCityName": "Cleveland",
        "teamId": "1610612739",
        "teamShortName": "Cleveland",
        "tricode": "CLE",
        "isAllStar": False,
        "divName": "Central",
        "reddit": "/r/ClevelandCavs",
        "isNBAFranchise": True,
        "confName": "East",
        "fullName": "Cleveland Cavaliers",
        "city": "Cleveland",
    },
    "1610612742": {
        "isNBAFranchise": True,
        "confName": "West",
        "city": "Dallas",
        "fullName": "Dallas Mavericks",
        "nickname": "Mavericks",
        "urlName": "mavericks",
        "teamId": "1610612742",
        "altCityName": "Dallas",
        "tricode": "DAL",
        "reddit": "/r/mavericks",
        "teamShortName": "Dallas",
        "divName": "Southwest",
        "isAllStar": False,
    },
    "1610612743": {
        "divName": "Northwest",
        "isAllStar": False,
        "tricode": "DEN",
        "teamShortName": "Denver",
        "teamId": "1610612743",
        "altCityName": "Denver",
        "nickname": "Nuggets",
        "urlName": "nuggets",
        "city": "Denver",
        "reddit": "/r/DenverNuggets",
        "fullName": "Denver Nuggets",
        "confName": "West",
        "isNBAFranchise": True,
    },
    "1610612765": {
        "divName": "Central",
        "isAllStar": False,
        "tricode": "DET",
        "teamShortName": "Detroit",
        "teamId": "1610612765",
        "altCityName": "Detroit",
        "nickname": "Pistons",
        "urlName": "pistons",
        "reddit": "/r/DetroitPistons",
        "fullName": "Detroit Pistons",
        "city": "Detroit",
        "confName": "East",
        "isNBAFranchise": True,
    },
    "1610612744": {
        "teamShortName": "Golden State",
        "tricode": "GSW",
        "isAllStar": False,
        "divName": "Pacific",
        "urlName": "warriors",
        "nickname": "Warriors",
        "altCityName": "Golden State",
        "teamId": "1610612744",
        "fullName": "Golden State Warriors",
        "reddit": "/r/warriors",
        "city": "Golden State",
        "isNBAFranchise": True,
        "confName": "West",
    },
    "1610612745": {
        "nickname": "Rockets",
        "urlName": "rockets",
        "teamId": "1610612745",
        "altCityName": "Houston",
        "tricode": "HOU",
        "teamShortName": "Houston",
        "divName": "Southwest",
        "isAllStar": False,
        "isNBAFranchise": True,
        "reddit": "/r/rockets",
        "confName": "West",
        "fullName": "Houston Rockets",
        "city": "Houston",
    },
    "1610612754": {
        "fullName": "Indiana Pacers",
        "city": "Indiana",
        "isNBAFranchise": True,
        "confName": "East",
        "tricode": "IND",
        "teamShortName": "Indiana",
        "divName": "Central",
        "isAllStar": False,
        "nickname": "Pacers",
        "urlName": "pacers",
        "reddit": "/r/pacers",
        "teamId": "1610612754",
        "altCityName": "Indiana",
    },
    "1610612746": {
        "urlName": "clippers",
        "nickname": "Clippers",
        "altCityName": "LA Clippers",
        "teamId": "1610612746",
        "teamShortName": "LA Clippers",
        "tricode": "LAC",
        "isAllStar": False,
        "divName": "Pacific",
        "isNBAFranchise": True,
        "reddit": "/r/laclippers",
        "confName": "West",
        "fullName": "LA Clippers",
        "city": "LA",
    },
    "1610612747": {
        "isAllStar": False,
        "divName": "Pacific",
        "teamShortName": "L.A. Lakers",
        "tricode": "LAL",
        "altCityName": "Los Angeles Lakers",
        "teamId": "1610612747",
        "urlName": "lakers",
        "nickname": "Lakers",
        "city": "Los Angeles",
        "reddit": "/r/lakers",
        "fullName": "Los Angeles Lakers",
        "confName": "West",
        "isNBAFranchise": True,
    },
    "1610612763": {
        "urlName": "grizzlies",
        "nickname": "Grizzlies",
        "altCityName": "Memphis",
        "teamId": "1610612763",
        "teamShortName": "Memphis",
        "tricode": "MEM",
        "isAllStar": False,
        "divName": "Southwest",
        "isNBAFranchise": True,
        "reddit": "/r/memphisgrizzlies",
        "confName": "West",
        "city": "Memphis",
        "fullName": "Memphis Grizzlies",
    },
    "1610612748": {
        "nickname": "Heat",
        "urlName": "heat",
        "teamId": "1610612748",
        "altCityName": "Miami",
        "tricode": "MIA",
        "teamShortName": "Miami",
        "divName": "Southeast",
        "isAllStar": False,
        "isNBAFranchise": True,
        "reddit": "/r/heat",
        "confName": "East",
        "city": "Miami",
        "fullName": "Miami Heat",
    },
    "1610612749": {
        "teamShortName": "Milwaukee",
        "tricode": "MIL",
        "isAllStar": False,
        "divName": "Central",
        "urlName": "bucks",
        "nickname": "Bucks",
        "altCityName": "Milwaukee",
        "teamId": "1610612749",
        "reddit": "/r/MkeBucks",
        "fullName": "Milwaukee Bucks",
        "city": "Milwaukee",
        "isNBAFranchise": True,
        "confName": "East",
    },
    "1610612750": {
        "tricode": "MIN",
        "teamShortName": "Minnesota",
        "divName": "Northwest",
        "isAllStar": False,
        "nickname": "Timberwolves",
        "urlName": "timberwolves",
        "teamId": "1610612750",
        "altCityName": "Minnesota",
        "fullName": "Minnesota Timberwolves",
        "reddit": "/r/timberwolves",
        "city": "Minnesota",
        "isNBAFranchise": True,
        "confName": "West",
    },
    "1610612740": {
        "fullName": "New Orleans Pelicans",
        "city": "New Orleans",
        "confName": "West",
        "isNBAFranchise": True,
        "isAllStar": False,
        "divName": "Southwest",
        "teamShortName": "New Orleans",
        "tricode": "NOP",
        "altCityName": "New Orleans",
        "reddit": "/r/nolapelicans",
        "teamId": "1610612740",
        "urlName": "pelicans",
        "nickname": "Pelicans",
    },
    "1610612752": {
        "fullName": "New York Knicks",
        "city": "New York",
        "isNBAFranchise": True,
        "confName": "East",
        "tricode": "NYK",
        "teamShortName": "New York",
        "divName": "Atlantic",
        "isAllStar": False,
        "nickname": "Knicks",
        "urlName": "knicks",
        "reddit": "/r/nyknicks",
        "teamId": "1610612752",
        "altCityName": "New York",
    },
    "1610612760": {
        "fullName": "Oklahoma City Thunder",
        "city": "Oklahoma City",
        "confName": "West",
        "isNBAFranchise": True,
        "isAllStar": False,
        "divName": "Northwest",
        "teamShortName": "Oklahoma City",
        "tricode": "OKC",
        "altCityName": "Oklahoma City",
        "reddit": "/r/thunder",
        "teamId": "1610612760",
        "urlName": "thunder",
        "nickname": "Thunder",
    },
    "1610612753": {
        "isNBAFranchise": True,
        "confName": "East",
        "fullName": "Orlando Magic",
        "city": "Orlando",
        "nickname": "Magic",
        "urlName": "magic",
        "teamId": "1610612753",
        "altCityName": "Orlando",
        "tricode": "ORL",
        "reddit": "/r/OrlandoMagic",
        "teamShortName": "Orlando",
        "divName": "Southeast",
        "isAllStar": False,
    },
    "1610612755": {
        "nickname": "76ers",
        "urlName": "sixers",
        "teamId": "1610612755",
        "altCityName": "Philadelphia",
        "tricode": "PHI",
        "teamShortName": "Philadelphia",
        "divName": "Atlantic",
        "isAllStar": False,
        "isNBAFranchise": True,
        "reddit": "/r/sixers",
        "confName": "East",
        "fullName": "Philadelphia 76ers",
        "city": "Philadelphia",
    },
    "1610612756": {
        "city": "Phoenix",
        "fullName": "Phoenix Suns",
        "confName": "West",
        "isNBAFranchise": True,
        "isAllStar": False,
        "divName": "Pacific",
        "teamShortName": "Phoenix",
        "tricode": "PHX",
        "altCityName": "Phoenix",
        "teamId": "1610612756",
        "reddit": "/r/suns",
        "urlName": "suns",
        "nickname": "Suns",
    },
    "1610612757": {
        "fullName": "Portland Trail Blazers",
        "city": "Portland",
        "confName": "West",
        "isNBAFranchise": True,
        "divName": "Northwest",
        "isAllStar": False,
        "tricode": "POR",
        "teamShortName": "Portland",
        "teamId": "1610612757",
        "reddit": "/r/ripcity",
        "altCityName": "Portland",
        "nickname": "Trail Blazers",
        "urlName": "blazers",
    },
    "1610612758": {
        "teamId": "1610612758",
        "altCityName": "Sacramento",
        "nickname": "Kings",
        "urlName": "kings",
        "divName": "Pacific",
        "isAllStar": False,
        "tricode": "SAC",
        "teamShortName": "Sacramento",
        "confName": "West",
        "reddit": "/r/kings",
        "isNBAFranchise": True,
        "city": "Sacramento",
        "fullName": "Sacramento Kings",
    },
    "1610612759": {
        "fullName": "San Antonio Spurs",
        "city": "San Antonio",
        "confName": "West",
        "isNBAFranchise": True,
        "divName": "Southwest",
        "isAllStar": False,
        "tricode": "SAS",
        "teamShortName": "San Antonio",
        "teamId": "1610612759",
        "reddit": "/r/nbaspurs",
        "altCityName": "San Antonio",
        "nickname": "Spurs",
        "urlName": "spurs",
    },
    "1610616833": {
        "isNBAFranchise": False,
        "confName": "East",
        "city": "Team",
        "fullName": "Team Team Durant",
        "urlName": "team_durant",
        "nickname": "Team Durant",
        "altCityName": "Team",
        "teamId": "1610616833",
        "teamShortName": "Team Durant",
        "tricode": "DRT",
        "isAllStar": True,
        "divName": "East",
    },
    "1610616834": {
        "teamId": "1610616834",
        "altCityName": "Team",
        "nickname": "Team LeBron",
        "urlName": "team_lebron",
        "divName": "West",
        "isAllStar": True,
        "tricode": "LBN",
        "teamShortName": "Team LeBron",
        "confName": "West",
        "isNBAFranchise": False,
        "fullName": "Team LeBron",
        "city": "Team",
    },
    "1610612761": {
        "isNBAFranchise": True,
        "confName": "East",
        "city": "Toronto",
        "fullName": "Toronto Raptors",
        "nickname": "Raptors",
        "urlName": "raptors",
        "teamId": "1610612761",
        "reddit": "/r/TorontoRaptors",
        "altCityName": "Toronto",
        "tricode": "TOR",
        "teamShortName": "Toronto",
        "divName": "Atlantic",
        "isAllStar": False,
    },
    "1610612762": {
        "fullName": "Utah Jazz",
        "city": "Utah",
        "confName": "West",
        "isNBAFranchise": True,
        "divName": "Northwest",
        "isAllStar": False,
        "tricode": "UTA",
        "teamShortName": "Utah",
        "teamId": "1610612762",
        "reddit": "/r/utahjazz",
        "altCityName": "Utah",
        "nickname": "Jazz",
        "urlName": "jazz",
    },
    "1810612762": {
        "fullName": "Utah Blue",
        "city": "Utah",
        "confName": "West",
        "isNBAFranchise": False,
        "divName": "Northwest",
        "isAllStar": False,
        "tricode": "UTB",
        "teamShortName": "Utah Blue",
        "teamId": "1810612762",
        "altCityName": "Utah",
        "nickname": "Jazz",
        "urlName": "utah_blue",
    },
    "1710612762": {
        "fullName": "Utah White",
        "city": "Utah",
        "confName": "West",
        "isNBAFranchise": False,
        "divName": "Northwest",
        "isAllStar": False,
        "tricode": "UTW",
        "teamShortName": "Utah White",
        "teamId": "1710612762",
        "altCityName": "Utah",
        "nickname": "Jazz",
        "urlName": "utah_white",
    },
    "1610612764": {
        "fullName": "Washington Wizards",
        "city": "Washington",
        "confName": "East",
        "isNBAFranchise": True,
        "divName": "Southeast",
        "isAllStar": False,
        "tricode": "WAS",
        "teamShortName": "Washington",
        "teamId": "1610612764",
        "reddit": "/r/WashingtonWizards",
        "altCityName": "Washington",
        "nickname": "Wizards",
        "urlName": "wizards",
    },
}
